# -*- coding: utf-8 -*-
"""Counting the number instances of each class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vKxY-QyKf9pb8Er_T1o_S5YLQfuKOOl
"""

#counting the number of instances
import os
from collections import defaultdict

# Path to the directory containing annotated frames
dataset_dir = "/content/drive/MyDrive/mgroad/FINAL/valid/labels"

# Initialize a defaultdict to store the counts for each class
class_counts = defaultdict(int)

# Iterate through each annotated frame
for filename in os.listdir(dataset_dir):
    if filename.endswith(".txt"):  # Assuming annotations are stored as text files
        with open(os.path.join(dataset_dir, filename), "r") as f:
            # Read lines from the annotation file
            lines = f.readlines()
            for line in lines:
                # Split the line to extract class label
                class_label = line.strip().split()[0]
                # Increment the count for the class label
                class_counts[class_label] += 1

# Print the counts for each class
for class_label, count in class_counts.items():
    print(f"Class: {class_label}, Count: {count}")